### ISSUE TITLE
Change Optimization Guides

### ISSUE THREAD

**Issue by Tikkle** [syscraft-mc/syscraft.dev#12]
https://github.com/syscraft-mc/syscraft.dev/blob/main/src/content/docs/en/server-performance.md

Great job so far guys, great content!

Might I suggest linking to YouHaveTrouble's "_[Minecraft Server Optimization Guide](https://github.com/YouHaveTrouble/minecraft-optimization)_" (an updated version of Celebrimbor's guide) and EterNity's [Paper-Chan.moe](https://paper-chan.moe/) "_[Paper vs Vanilla](https://paper-chan.moe/paper/)_" and "_[Paper Chan's Little Guide to Minecraft Server Optimization!](https://paper-chan.moe/paper-optimization/)_" blog posts as they are up-to-date with Minecraft's latest (1.19.4) release and paper's config options.

EterNity also does an amazing job of describing how to optimize a server but keep it as close to a Vanilla feeling as possible in "_[Paper vs Vanilla](https://paper-chan.moe/paper/)_".

Edit: It also helps that EterNity is a current Paper Community Team member as of Mar 30, 2023

**Comment by Turbotailz** [comment]
PRs are welcome 😉

**Comment by Tikkle** [comment]
#13
